export const banks = [
  { value: "HSBC", label: "HSBC" },
  { value: "Citibank", label: "Citibank" },
  { value: "Standard Chartered", label: "Standard Chartered" },
  { value: "BNP Paribas", label: "BNP Paribas" },
  { value: "Santander", label: "Santander" },
  { value: "Deutsche Bank", label: "Deutsche Bank" },
  { value: "Barclays", label: "Barclays" },
  { value: "Credit Suisse", label: "Credit Suisse" },
  { value: "ING Group", label: "ING Group" },
  { value: "UniCredit", label: "UniCredit" },
  { value: "Société Générale", label: "Société Générale" },
  { value: "Lloyds Banking Group", label: "Lloyds Banking Group" },
  { value: "Royal Bank of Scotland (RBS)", label: "Royal Bank of Scotland (RBS)" },
  { value: "Nordea Bank", label: "Nordea Bank" },
  { value: "Danske Bank", label: "Danske Bank" },
  { value: "KBC Group", label: "KBC Group" },
  { value: "Raiffeisen Bank International", label: "Raiffeisen Bank International" },
  { value: "Commerzbank", label: "Commerzbank" },
  { value: "ABN AMRO", label: "ABN AMRO" },
  { value: "JPMorgan Chase", label: "JPMorgan Chase" },
  { value: "Bank of America", label: "Bank of America" },
  { value: "Wells Fargo", label: "Wells Fargo" },
  { value: "Goldman Sachs", label: "Goldman Sachs" },
  { value: "Morgan Stanley", label: "Morgan Stanley" },
  { value: "TD Bank", label: "TD Bank" },
  { value: "PNC Financial Services", label: "PNC Financial Services" },
  { value: "Capital One", label: "Capital One" },
  { value: "BBVA USA", label: "BBVA USA" },
  { value: "Fifth Third Bank", label: "Fifth Third Bank" },
  { value: "M&T Bank", label: "M&T Bank" },
  { value: "KeyBank", label: "KeyBank" },
  { value: "SunTrust Bank", label: "SunTrust Bank" },
  { value: "Agricultural Bank of China", label: "China Construction Bank" },
  { value: "Bank of China", label: "Bank of China" },
  { value: "ICBC", label: "ICBC" },
  { value: "Mizuho Bank", label: "Mizuho Bank" },
  { value: "China Merchants Bank", label: "China Merchants Bank" },
  { value: "SMBC", label: "SMBC" },
  { value: "UBS Group AG", label: "UBS Group AG" },
  { value: "CaixaBank", label: "CaixaBank" },
  { value: "UniCredit", label: "UniCredit" },
  { value: "Intesa Sanpaolo", label: "Intesa Sanpaolo" },
  { value: "Nordea Bank", label: "Nordea Bank" },
  { value: "Swedbank", label: "Swedbank" },
  { value: "DNB ASA", label: "DNB ASA" },
  { value: "Handelsbanken", label: "Handelsbanken" },
  { value: "KBC Group", label: "KBC Group" },
  { value: "ING Group", label: "ING Group" },
  { value: "Rabobank", label: "Rabobank" },
  { value: "ABN AMRO Bank", label: "ABN AMRO Bank" },
  { value: "Standard Chartered Bank", label: "Standard Chartered Bank" },
  { value: "Lloyds Banking Group", label: "Lloyds Banking Group" },
  { value: "Royal Bank of Scotland", label: "Royal Bank of Scotland" },
  { value: "HSBC Holdings plc", label: "HSBC Holdings plc" },
  { value: "BNP Paribas", label: "BNP Paribas" },
  { value: "Natixis", label: "Natixis" },
];
